### ISSUE TITLE
Xiphos crashes when I searched the DRC module for eID

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#1222]
With the **DRC** module version 2.0 open, whenever I search for **eID**, **Xiphos** crashes!

I know this is odd, but I can search using **PocketSword** in this old module for **eID**, and get 1334 results!
The peculiarity is that every result is the last verse of a chapter, 
and the results displayed each include the OSIS milestone `<chapter eID="gen#" osisID="Book.#"/>`.
btw. Other word searches which include results that are in the last verse of a chapter also display the milestone.

cf. Searching other Bible modules (e.g. **KJV**) for **eID** gives no results, and Xiphos doesn't crash.

I wonder what it is about the **DRC** module that trigger this weird behaviour?

**Comment by karlkleinpaste** [comment]
I tried searching DRC for eID, it worked fine, no crash. If I had to guess, your old Xiphos built with Sword 1.8 has a problem that is now resolved.

![Image](https://github.com/user-attachments/assets/b5a589c0-51e8-4e7b-9b92-a42282e4b019)

**Comment by DavidHaslam** [comment]
Thanks, @karlkleinpaste 

I'm relieved to learn that the latest build of **Xiphos** doesn't crash. Fr Cyrille has confirmed that too.
I'm still puzzled why we get 1334 results for the **DRC** module, but none for (eg) the **KJV** module.
What could it be about how the **DRC** module was made that exposes these OSIS **eID** milestones to the search feature?

**Comment by DavidHaslam** [comment]
After installing **Xiphos 4.3.0 x64** in my Windows laptop PC, I tried again to search the **DRC** module for **eID**.

Sad to report that **Xiphos** still crashed!!!!

As I do not have authority to **Reopen Issue**, please would @karlkleinpaste do so.

_Please contact me if you require any further information_.

**Comment by karlkleinpaste** [comment]
Sorry, I can't confirm this. Just-released 4.3.0 on Windows 11:

![Image](https://github.com/user-attachments/assets/351f927e-52e3-4b85-bd34-3f6eaf681d3b)

Also succeeds using Win64 binary under Wine on Linux.
Also succeeds in native Linux build.

It appears your environment has a problem. Re-install module? Or at least re-index?

If it matters, I have DRC 2.0 from Crosswire's own repo.

**Comment by DavidHaslam** [comment]
Bravo! @karlkleinpaste 

I too have DRC 2.0 from Crosswire.
After deleting the Index and Re-indexing, I tried again and this time Xiphos no longer crashed!

**Comment by DavidHaslam** [comment]
A mystery remains!  @karlkleinpaste 

Why, out of all the available Bible modules based on OSIS XML, is it _only_ the **DRC** module that returns results for **the last verse of every chapter** after a search for **eID** ?

Does what I observed with **PocketSword** provide any further clue?

**Comment by karlkleinpaste** [comment]
`mod2imp DRC > drc.imp`
Look at the result.
There are eID elements only on last verses of each chapter.

**Comment by DavidHaslam** [comment]
Yes, indeed - that's precisely what I get!

For the DRC module _only_, if I search for **chapter** or **eID** or **osisID**, I get the same set of results.
What could it be about this module that the words in those OSIS milestone elements all end up as being part of the search index?
Is there an "off by one" error somewhere in the SWORD engine, that for some obscure reason only affects this module?

**Comment by karlkleinpaste** [comment]
I don't know, but you're far away from asking questions about Xiphos at this point. This is a Sword or OSIS question. You can get the same answers with `diatheke` and not involve Xiphos at all.

**Comment by dmsmith** [comment]
I agree it is not a problem with Xiphos.

This sounds like a possible bug in osis2mod or in the module. Perhaps remaking the module would change what you find.

From what I remember:

Troy wanted the verse milestone tags, both begin and end to not be in the module. I think that there may have been an exception made for the last verse of the chapter because of the colophon in books which are after the final chapter in a book but in the index are appended to the last verse of the book.

At one point, osis2mod kept the milestones for verse starts and ends in the module. As these don’t display Chris Little and I were fine with them, but Troy said to remove them. I’m pretty sure that the code merely comments out where they were output.
